name: Find Sentinel-2 Images

on:
  workflow_dispatch:

  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write

jobs:
  find-sentinel2:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Find Sentinel-2 images
        run: |
          python find_sentinel2.py

      - name: Save Sentinel-2 search result
        run: |

          git config user.name "github-actions[bot]"

          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

          git add sentinel2_search.json

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "Update Sentinel-2 search result"

          git push
