name: Find Archivable Fires 2026

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  find-archivable-fires:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Find archivable fires
        run: |
          python find_archivable_fires_2026.py

      - name: Save result
        run: |

          git config user.name "github-actions[bot]"

          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

          git add archivable_fires_2026.json

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "Find archivable fires 2026"

          git push
