name: Process Five Ready Fires 2026

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process-five-fires:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy rasterio

      - name: Process five fires
        env:
          CDSE_CLIENT_ID: ${{ secrets.CDSE_CLIENT_ID }}
          CDSE_CLIENT_SECRET: ${{ secrets.CDSE_CLIENT_SECRET }}
        run: |
          python process_five_ready_fires_2026.py

      - name: Save five-fire results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add five_fires_burned_area_result.json
          git add burned_area_mask_fire_*.tif

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "Process five ready fires 2026"

          git pull --rebase origin main

          git push origin main
