name: Test Calculate Burned Area

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-burned-area:

    runs-on: ubuntu-latest

    steps:

      # ------------------------------------------------------
      # دریافت Repository
      # ------------------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4


      # ------------------------------------------------------
      # نصب Python
      # ------------------------------------------------------

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # ------------------------------------------------------
      # نصب کتابخانه‌ها
      # ------------------------------------------------------

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests rasterio pyproj


      # ------------------------------------------------------
      # اجرای محاسبه Burnt Area
      # ------------------------------------------------------

      - name: Run burned area calculation
        env:
          CDSE_CLIENT_ID: ${{ secrets.CDSE_CLIENT_ID }}
          CDSE_CLIENT_SECRET: ${{ secrets.CDSE_CLIENT_SECRET }}
        run: |
          python calculate_burned_area.py


      # ------------------------------------------------------
      # ذخیره نتیجه در Repository
      # ------------------------------------------------------

      - name: Save burned area result
        run: |

          git config user.name "github-actions[bot]"

          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

          git add burned_area_result.json

          if git diff --cached --quiet; then
            echo "No result changes."
            exit 0
          fi

          git commit -m "Calculate latest burned area"

          git push
